### PR TITLE
add ruby 2.6 to travis

### PR DESCRIPTION
**Pull request by colby-swandale**
This PR adds ruby 2.6.0 into Travis.

### CODE REVIEW

**Comment by colby-swandale** [comment]
Note that i didn't update `.ruby-version` as well. I wasn't sure at what point that can be changed, so i will leave it until this has been merged and 2.6 has been confirmed as being officially supported.

**Comment by colby-swandale** [comment]
Thinking about my last comment, i guess it's already offically supported due to `dud_you_mean` being shipped with ruby ¯\_(ツ)_/¯

**Comment by yuki24** [comment]
Maybe we can delete the `.ruby-version` entirely. Happy new year and thanks for your first contribution in 2019!

**Comment by colby-swandale** [comment]
That sounds like a good idea @yuki24!

**Pull request merged**
