### PR TITLE
Simply turn into a string and downcase

### PR DESCRIPTION
**Pull request by nobu**
`Symbol#to_s` returns frozen string now.

### CODE REVIEW

**Comment by yuki24** [comment]
Thanks!

**Comment by MSP-Greg** [comment]
To all,

Thanks for the fix.  JFYI, this is causing errors in both spec & test-all when run in Ruby master without `--disable=did_you_mean`.  Probably the reason for the PR.

Due to:
https://github.com/ruby/ruby/commit/6ffc045a817fbdf04a6945d3c260b55b0fa1fd1e
[EXPERIMENTAL] Make Symbol#to_s return a frozen String
Thu Sep 26 10:23:02 2019 +0200

**Comment by eregon** [comment]
@MSP-Greg Could you point to a failure in a CI log? Or is it only happening locally?

**Comment by MSP-Greg** [comment]
@eregon

ruby/ruby builds are from the build folder, so they may not have did_you_mean enabled, as it is a bundled gem.  ruby-loco runs tests from install, so it is enabled.  See below:
```
NoMethodError#message calls receiver.inspect only when calling Exception#message FAILED
Expected [:inspect_called, :inspect_called]
 to equal [:inspect_called]

/ruby/spec/ruby/core/exception/no_method_error_spec.rb:86:in `rescue in block (2 levels) in <top (required)>'
/ruby/spec/ruby/core/exception/no_method_error_spec.rb:80:in `block (2 levels) in <top (required)>'
/ruby/spec/ruby/core/exception/no_method_error_spec.rb:45:in `<top (required)>'
```
```
  1) Error:
TestRDocRIDriver#test_display_name_not_found_class:
FrozenError: can't modify frozen String: ""
    /install/lib/ruby/gems/2.7.0/gems/did_you_mean-1.3.0/lib/did_you_mean/spell_checker.rb:47:in `downcase!'
    /install/lib/ruby/gems/2.7.0/gems/did_you_mean-1.3.0/lib/did_you_mean/spell_checker.rb:47:in `normalize'
    /install/lib/ruby/gems/2.7.0/gems/did_you_mean-1.3.0/lib/did_you_mean/spell_checker.rb:13:in `correct'
    /install/lib/ruby/2.7.0/rdoc/ri/driver.rb:1286:in `lookup_method'
```

I patched the method:
```ruby
    def normalize(str_or_symbol) #:nodoc:
      str_or_symbol.to_s.downcase.tr("@", "").dup
    end
```
As you know, it only affects people using very new versions of ruby-head.  Didn't you do the commit?

**Comment by yuki24** [comment]
@MSP-Greg Interesting. I wonder if there is a case where the `#downcase` method also returns a frozen string. If that's the case, I'd be happy to apply your patch above.

**Comment by MSP-Greg** [comment]
@yuki24

I've been writing/refactoring too many tests lately.  Hence, write bullet-proof code.

>  where the #downcase method also returns a frozen string

Well, a few days ago, `Symbol#to_s` wasn't frozen...

It's probably fine the way it is, and @nobu is certainly aware of what may be changing in the future...

**Comment by nobu** [comment]
@MSP-Greg You might want to write `#downcase!`, I think.

**Comment by eregon** [comment]
Actually, the did_you_mean tests failed on https://github.com/ruby/ruby/runs/236956239 but nobody noticed since that's run by ignored the exit status (https://github.com/ruby/ruby/blob/550a6a6bc1be4ff9aa6b65f6ad9b45c3fa2d1344/.github/workflows/ubuntu.yml#L83)

**Comment by eregon** [comment]
@yuki24 Could you make a release of `did_you_mean` with this fix? :pray: 
This seems to be the only way to make the `did_you_mean` tests in ruby/ruby's CI pass.

**Comment by MSP-Greg** [comment]
@nonu

> You might want to write #downcase!, I think.

I'm probably mistaken, but isn't that true iif  `str` is the final return value?

I ran the tests locally without the final `.dup` call shown above, and they ran fine.  IOW, the method was simply
`str_or_symbol.to_s.downcase.tr '@', ''`

**Comment by yuki24** [comment]
released as part of [`v1.3.1`](https://github.com/yuki24/did_you_mean/releases/tag/v1.3.1).

**Comment by eregon** [comment]
@yuki24 Thank you, did_you_mean tests pass on ruby/ruby now: https://github.com/ruby/ruby/pull/2503

**Pull request merged**
